from lib import *
print(f'Tiempo de ejecución: {ft}')
print('----------------------------------------------------------')
print('Hilo principal o hilo 1')
print(lista_numeros)
print('----------------------------------------------------------')
print('Usando hilo 4')
print(f'Tiempo de ejecución: {tf}')
print(global_arrayNum)
print(lista_hilos)
#timemaker()
